name: docs

on: 
  workflow_dispatch:

jobs:
  docs:        
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repositry
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry and setup cache
      uses: Gr1N/setup-poetry@v4
    
    - name: Install dependencies
      run: poetry install

    - name: Build docs
      run: bash run.sh docs

    - name: Recommit docs
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'bot: update docs [skip ci]'
        file_pattern: ./docs/*
        commit_user_name: trallnag-bot
        commit_user_email: tim.and.trallnag+code@gmail.com
